### ISSUE TITLE
Link Descriptions

### ISSUE THREAD

**Issue by Michaelgathara** [4shub/boost.avoice.info#14]
No way to customize the descriptions of the links when shared over social media.

A descriptions.txt file fed into <meta name="description"> could fix this

**Comment by 4shub** [comment]
Meta description sounds like a good idea, probably will add a new field to METADATA called `seo-description` or something

**Comment by 4shub** [comment]
Done, you can add to metadata these two columns above `SUMMARY`

```
SEO_IMAGE: https://image.com
SEO_DESCRIPTION: blah description
```
